# Generated by Django 5.2.15 on 2026-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.CharField(blank=True, choices=[('medical', 'Medical Reference'), ('conversational', 'Conversational')], max_length=15, null=True),
        ),
    ]
