# Generated by Django 5.2.15 on 2026-06-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='citations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
