# Generated by Django 5.2.15 on 2026-06-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rewritten_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
