# Generated by Django 5.2.15 on 2026-07-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='complete', max_length=12),
        ),
    ]
